### ISSUE TITLE
Enable gene only Prioritisation

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#125]
Involves #110 

This would be a real boon to most users who have their own variant prioritisation pipeline and all they want is a gene priority score from the semantic similarity part.

This is currently linked with varint filtering so might take a bit of work to fully decouple.
- [x] Investigate impact on spring-boot-autoconfigure module
- [x] Create standalone variant prioritisation REST service

**Comment by damiansm** [comment]
More detail on db split:

Splitting the database. We’re going to try and split it so that the prioritiser package can run independently of the rest of the application. The other advantage of this is we can then provide both hg37 and hg38 data in the same release and independently release changes for the other data. To do this we’ll: a. Create at least two h2 databases – variant and phenotype plus maybe a ‘common’ one containing shared data, like diseases, models, gene symbols.
b. Probably the next release we’ll look into changing the database back-ends so that they use a suitable engine for the type of data stored – document for the variant data, graph for the phenotype data and probably relational for the common.
c. Update the core and spring-boot-autoconfigure libraries to handle the split.
d. The split and library updates will have to happen together, but it will make the database backend changes easier as a second step.
e. We’re going to have to think of some sensible naming conventions for these – possibly {name}-{compatible-version}-{build-date} e.g. variant-8.0.0-20161104
f. In order not to have inconsistent gene ids between what’s in Jannovar and the actual database we’re going to need some way of freezing/synchronising the right bits of this data.
