### ISSUE TITLE
Proband sample ID should be specified in input 

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#147]
RawScoreGeneScorer will produce potentially incorrect scores when a multi-sample VCF is run in which the proband is not the first sample, assuming AUTOSOMAL_RECESSIVE modeOfInheritance is being run.

This can be fixed by knowing what sample ID the proband has and using this is the RawScoreGeneScorer. Also check the RankedScoreGeneScorer.

**Comment by julesjacobsen** [comment]
- [ ] SampleDataFactory,  SampleData and PedigreeFactory are unnecessarily coupled. There is no real requirement for a  SampleDataFactory - the Pedigree creation and VariantFactory are not required here. A simple SampleData.Builder is all that's needed. 
- [ ] SampleData should be renamed AnalysisResults as the results are not the same as the input sample and requires a probandSampleId field.
- [ ] PedigreeFactory needs the probandSampleId as input

**Comment by julesjacobsen** [comment]
- [ ] Update WEB!

**Comment by julesjacobsen** [comment]
@visze commented that clinicians found this confusing having to specify a proband as the affected were already identified in the pedigree. It should be possible to choose the/a proband sample present in the VCF and marked as affected in the pedigree and work from this. 

To be discussed whether this is safe to do in cases where multiple affected are present in the VCF and whether this will lead to confusion over which sample the Exomiser is analysing.

**Comment by julesjacobsen** [comment]
@damiansm @pnrobinson Can you comment on whether you think this is necessary or not? I think we should keep it as required partly to keep things simple, but also in order to ensure that the users are explicitly marking the sample they want to run the analysis on.

**Comment by damiansm** [comment]
Is it possible to have a halfway house and take affectedSample[0] as
proband if they have not defined it?

**Comment by julesjacobsen** [comment]
Yep, I could do that. For simple trios with a single affected, this would be easy. For a family with affected parent and child, would assume the child.

Where it gets harder is if there are large pedigrees with multiple affected in different families. If more than one of these is present in the VCF sample then we need to have the proband specified as they may have different phenotypes. Presumably, not wildly differing, but possibly enough to make a difference especially if there are actually overlapping disorders.

For multiple affected siblings I think we should insist on a proband being specified - again, they could have slightly different phenotypes. The pedigree doesn't take this into account - people are assumed to be in a boolean state of affectedness, where in reality there could be variation.

Do you agree with this? I can make assumptions for the simple cases, but then require specific input for complex cases?

**Comment by visze** [comment]
I do not understand the problem here. Everyone is the proband if he is affected. If you really need only one you can randomly choose one (like affectedSampel[0]).

Reasons:
1. You put in phenotype terms of phenotypes you want to analyse (no matter if one or more samples share the phenotypes).
2. You add the pedigree matching to the used phenotypes.
3. Yes the phenotypes can vary in a family even if they have the same disease. But
3.1 Clinicians use a mostly a consensus phenotype or the major phenotypes all probands share. 
3.2 We are dealing with Mendelian diseases, so we have only one gene affected and the phenotype algorithms should be robust enough to detect the gene even if the phenotype is slightly different. (that what we always testing with the phenotype algorithms, e.g. adding random terms).
4. The clinicians here at the Charité did not understand the option, too.
5. Exomiser is for Mendelian not for complex diseases

**Comment by pnrobinson** [comment]
I agree with Max that fior the Exomiser there is no point in specifying the proband -- we only need to know the affecteds in the pedigree.

**Comment by julesjacobsen** [comment]
This is only required for AR scenarios with multiple samples present in the VCF. The reason being in the current implementation we compare the best scoring hom_alt with the average of the top two het scores for a possible compound het scenario. In either case, we need to know who the proband is in order to check the genotype of the allele for that sample. This then gives us the variant score for the gene and allows us to mark which variant(s) are contributing to this score. So what do you recommend as an alternative, non-proband approach?

**Comment by damiansm** [comment]
I don't know what Jannovar does with multiple-affected in the pedigree but
I am assuming if variants have passed the inheritance filter they should
have the same genotype for all affecteds? If that simple scenario is true
then just picking the first affected sample randomly should be fine.

Are there some edge cases though that come through Jannovar i.e. some
variant that is hom_alt in one affected and het in another affected and
passes via the cmphet filter. I think even in the edge case just picking
one is better than specifying the proband.

Not sure if the rule should pick a child over parents from
multiple-affecteds rather than randomly picking the first one though.
Pragamatically, randomly picking one of the affected sibs at the bottom of
the pedigree seems the right approach

**Comment by pnrobinson** [comment]
There might be edge cases were the genotype of an affected is incomplete, but this will be impossible to know in advance, and I agree that just picking a proband is the best option. Might be worth revisiting this is we can find a dataset in which practical issues occur.

-Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by damiansm** [comment]
Thinking some more. Is "most extreme" genotype in all affecteds what we
need when we are doing scoring i.e. if it is hom_alt in ANY of the
affecteds score it as a hom_alt, otherwise it should be getting scored
under the cmphet model.

**Comment by julesjacobsen** [comment]
Having spoken to a couple of people here, there was no confusion about having a requirement on defining a proband. There is always the focus of a study for a report. Even if there are two affected siblings, each will have their own report. 

The code for figuring out a proband in more complex cases than a duo/trio, where there are leaf-node children starts to get complicated. We have no control over the complexity of the pedigrees coming in and cannot assume the simplest, most common case, will be sufficient. As such, this requires robust, well-tested code which takes time to code and test sufficiently. After that there is the burden of maintenance and added complexity in the system. All of this can simply be avoided by asking for a proband. 

While some clinicians may be confused as to the relevance of this in simple cases, they will be able to provide the necessary information. Whilst this may not be strictly necessary in all cases, it's not a big ask of the user, we can avoid weird edge cases, and we already have working code.
