### ISSUE TITLE
Update Jannovar to 0.17.0

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#148]
This will break the ModeOfInheritance and require updating of the HTSJDK lib.

https://github.com/charite/jannovar/blob/master/CHANGELOG.md

**Comment by visze** [comment]
0.17.1 will not be released on maven Central. But 0.17.1 will not affect
exomiser because it is still using ucsc only. So we can use 0.17 instead.

0.18.0 will be of more interest. There will be a field for the entrez
geneid. Then exomiser will be able to Switch between different transcript
db.

* UCSC
* RefSeq + RefSeq curated
* Ensemble + Ensemble curated
* CCDS

Even Mouse transcript db will be possible providing an necessary feature
for the 'mouseomizer'

Am 07.11.2016 18:10 schrieb "Jules Jacobsen" <notifications@github.com>:

This will break the ModeOfInheritance and require updating of the HTSJDK
lib.

https://github.com/charite/jannovar/blob/master/CHANGELOG.md

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/exomiser/Exomiser/issues/148>, or mute the thread

**Comment by julesjacobsen** [comment]
Ah, nice to hear about the improvements coming in 0.18.0.

**Comment by julesjacobsen** [comment]
commit f4da6a89fe6035a103284b53e59e004019f18059
