### ISSUE TITLE
Errors in OrganismPhenotypeMatches

### ISSUE THREAD

**Issue by drseb** [exomiser/Exomiser#168]
I am still not able to get a running version for developers.

Current errors are
 - `/exomiser-core/src/main/java/org/monarchinitiative/exomiser/core/prioritisers/util/OrganismPhenotypeMatches.java` (line 67): _Type mismatch: cannot convert from Object to Set<String>_
- `/exomiser-core/src/main/java/org/monarchinitiative/exomiser/core/prioritisers/util/OrganismPhenotypeMatches.java` (line 70): _The type Collections does not define unmodifiableSet(Collection<String>) that is applicable here_
 

Any help on that? All I did was `mvn clean install` and `mvn eclipse:eclipse` and an import to eclipse.

**Comment by julesjacobsen** [comment]
Odd - so you can compile and build the project and I suppose it runs ok on one of the test analyses? Could it be an Eclipse issue perhaps? I've had no issues with IntelliJ.

What does ``mvn eclipse:eclipse`` do?  Do you need it? Sorry - I can't help you with Eclipse as I don't use it. Perhapse @vise could help?

**Comment by julesjacobsen** [comment]
This might be an Eclipse bug -http://stackoverflow.com/questions/25226415/java-8-generic-type-inference-fails-on-method-reference#25313246

Have you considered IntelliJ? It's very nice... http://www.jetbrains.com/idea/

**Comment by drseb** [comment]
ok. @visze and I are investigating.

**Comment by visze** [comment]
`mvn eclipse:eclipse` just creates a eclipse project including all dependencies. It should proper work if every dependency is set in the pom.

Running `mvn clean install package` works fine for me. Then I run `mvn eclipse:clean eclipse:eclipse` to clean my projects and build new ones.

I have the same error but I can compile it. The error is due to the warning/error settings of the IDE. If you change the settings it is fine (Type mismatch). But my error is on line 94 and not before....

The difference might be due to different eclipse versions. I am using neon, the actual one, @drseb an older version. He will try to run it with neon to see if it works.

Please keep the IDE discussion away! This is not helpful. Otherwise I would like to recommend emacs

**Comment by julesjacobsen** [comment]
Hah! No, I agree, it shouldn't matter. So long as it doesn't pollute the code base with extra IDE-specific stuff, aids the developer and works, all is well.

**Comment by damiansm** [comment]
Agree I hate IDE discussions and hate being told to change. However Jules
did manage to bully me into IntelliJ and have to say it magically fixes
most development issues. When things are missing it just pops up with
suggested solutions which nearly always seem to fix the problem.

**Comment by pnrobinson** [comment]
Never saw this problem with emacs...but my first impressions with intelliJ of the last 2 weeks are pretty good. Eclipse never really worked that well for shared projects because of the way it shares or doesnt share project settings....

**Comment by drseb** [comment]
Anyway. No problems with newest eclipse version so far. Thanks.
