### ISSUE TITLE
Exception in thread "main" org.monarchinitiative.exomiser.core.analysis.SampleMismatchException: proband sample name not specified

### ISSUE THREAD

**Issue by OskarSchnappauf** [exomiser/Exomiser#232]
Dear Exomiser team,

I use Exomiser 7.2.1  since some time and I am loving it. Very impressive work and I am very grateful for your effort. 
However, I tried to use Exomiser 8.0.1 with the same vcd file and ped file as before and I get the following error:

Exception in thread "main" org.monarchinitiative.exomiser.core.analysis.SampleMismatchException: proband sample name not specified. Expected single sample VCF but got 3 sample names - [1643748, 1643749, 1643751]. Please check your sample and analysis files match.

I browsed your issues and could only find the recommendation to put the affected individual as the first individual in the vcf file. That's true in my case, and I still get the error.

I would highly appreciate your help.
Thank you!

**Comment by visze** [comment]
Hi Oskar,

Thank you for using exomiser. Since version 8 there is a new setting in the configuration file called `proband`.  Have a look at the example https://github.com/exomiser/Exomiser/blob/master/exomiser-cli/src/main/resources/examples/test-analysis-exome.yml

Here you have to add one affected sample ID. We had a lot of discussion if we need this extra setting or if we just came use one random affected in the pedigree. But for now we have this parameter which is obligatory when using more than one sample.

I also recognized that the documentation is lacking here. I think we should revise the manual and highlight clearly what changed in a new release especially for the end users.

I hope this solves your issue.

**Comment by OskarSchnappauf** [comment]
Hi Max,

Thank you so much for your quick reply! It is working fine when I use --proband, thank you!
Exomiser is great and I wanna try to use it on WGS as well soon.
Have a great day!
And Thanks again,
Oskar
