### ISSUE TITLE
Allow interval filter to include multiple regions

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#246]

**Comment by garrett-stevens** [comment]
Would this be by adding more regions to the YAML file, or were you thinking of supporting reading in regions from e.g. a BED file? I vote for the BED file option if it's still undecided.

**Comment by julesjacobsen** [comment]
What's your argument in favour of the BED file option?

**Comment by garrett-stevens** [comment]
It just seem like the standard way regions are specified, at least with the people I work with. I actually end up doing something similar a lot, where I'll filter a VCF with a BED file before using Exomiser on it. Usually this is because whoever I'm doing the analysis for doesn't want the `variantEffectFilter`, but they also only want to look at certain regions (which they provide me in a BED file), so filtering through the BED file first is a must for efficiency's sake.

It's not a big deal either way, though, I just thought I'd throw my opinion out there.

**Comment by julesjacobsen** [comment]
Upcoming in 10.1.0 - 

e45bd8e87c61f19bf885eb71b711ffd32974c8fd
6668a4a627a4b81251b4ac18f346c969b0aa72d6
b017d7e3af379fc87ea67ef0a8c121998752684b
